import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { aiService } from './services/aiService';
import { initializeDatabase, closeDatabase, seedDatabase } from './db/database';
import { getTodayTasks, getActiveGoals, getTodaySessions } from './db/queries';

// Load environment variables from .env file
dotenv.config();

// Initialize database on app start
initializeDatabase();
seedDatabase();

// Initialize AI service with API key from environment if available
if (process.env.GEMINI_API_KEY) {
  aiService.setApiKey(process.env.GEMINI_API_KEY);
  console.log('✓ Gemini API key loaded from .env');
} else {
  console.warn('⚠ GEMINI_API_KEY not found in .env file');
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    closeDatabase();
    app.quit();
  }
});

app.on('before-quit', () => {
  closeDatabase();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window on the dock
  // icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// ─── IPC Handlers for File Operations ─────────────────────────────────
// Open file dialog to select markdown file
ipcMain.handle('import-plan-file', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [
      { name: 'Markdown Files', extensions: ['md'] },
      { name: 'All Files', extensions: ['*'] },
    ],
  });

  if (result.canceled) {
    return null;
  }

  const filePath = result.filePaths[0];
  if (!filePath) return null;

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return {
      filePath,
      fileName: path.basename(filePath),
      content,
    };
  } catch (error) {
    console.error('Error reading file:', error);
    return null;
  }
});

// Read plan file directly from a given path
ipcMain.handle('read-plan-file', async (event, filePath: string) => {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return {
      filePath,
      fileName: path.basename(filePath),
      content,
    };
  } catch (error) {
    console.error('Error reading file:', error);
    return null;
  }
});

// ─── IPC Handlers for AI Operations ────────────────────────────────────
// Set Gemini API Key
ipcMain.handle('set-gemini-api-key', async (event, apiKey: string) => {
  try {
    aiService.setApiKey(apiKey);
    return { success: true, message: 'API key set successfully' };
  } catch (error) {
    console.error('Error setting API key:', error);
    return { success: false, message: 'Failed to set API key' };
  }
});

// Get stored API key from environment or initialize
ipcMain.handle('get-stored-api-key', async () => {
  try {
    const apiKey = process.env.GEMINI_API_KEY || null;
    if (apiKey) {
      console.log('✓ Returning API key from environment to renderer');
      aiService.setApiKey(apiKey);
      return { success: true, key: apiKey };
    }
    console.log('ℹ No API key found in environment (process.env.GEMINI_API_KEY is empty)');
    return { success: false, key: null };
  } catch (error) {
    console.error('Error getting stored API key:', error);
    return { success: false, key: null };
  }
});

// Analyze schedule with Gemini
ipcMain.handle('analyze-schedule', async (event, mdContent: string) => {
  try {
    if (!aiService.isInitialized()) {
      return {
        success: false,
        error: 'AI service not initialized. Please provide a Gemini API key.',
      };
    }
    const analysis = await aiService.analyzeSchedule(mdContent);
    return { success: true, data: analysis };
  } catch (error) {
    console.error('Error analyzing schedule:', error);
    return { success: false, error: (error as Error).message };
  }
});

// Generate study tips
ipcMain.handle('generate-study-tips', async (event, mdContent: string) => {
  try {
    if (!aiService.isInitialized()) {
      return {
        success: false,
        error: 'AI service not initialized. Please provide a Gemini API key.',
      };
    }
    const tips = await aiService.generateStudyTips(mdContent);
    return { success: true, data: tips };
  } catch (error) {
    console.error('Error generating study tips:', error);
    return { success: false, error: (error as Error).message };
  }
});

// Estimate workload
ipcMain.handle('estimate-workload', async (event, mdContent: string) => {
  try {
    if (!aiService.isInitialized()) {
      return {
        success: false,
        error: 'AI service not initialized. Please provide a Gemini API key.',
      };
    }
    const workload = await aiService.estimateWorkload(mdContent);
    return { success: true, data: workload };
  } catch (error) {
    console.error('Error estimating workload:', error);
    return { success: false, error: (error as Error).message };
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
