import { app, BrowserWindow } from 'electron';
import * as dotenv from 'dotenv';
import { initializeDatabase, closeDatabase, seedDatabase } from './main/db/database';

// Load environment variables from .env file
dotenv.config();

// Initialize database on app start
initializeDatabase();
seedDatabase();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    closeDatabase();
    app.quit();
  }
});

app.on('before-quit', () => {
  closeDatabase();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window on the dock
  // icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// ─── IPC Handlers for File Operations ─────────────────────────────────
// NOTE: File handlers are registered in src/main/handlers/ipcHandlers.ts
// via setupAllHandlers() to avoid duplicate registration

// ─── IPC Handlers for AI Operations ────────────────────────────────────
// NOTE: AI handlers are managed by aiService locally via Ollama/TinyLLaMA
// The agent pipeline handles LLM calls through src/main/services/messageReceiver.ts

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
